import { useSettingsRoutes } from "@/hooks/use-settings-routes";
import { BarChart, ChevronRight } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import BddManagerSection from "./components/manage-bdd-section";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ParamsPage = () => {
  return (
    <div>
      <div>
        <p className="text-sm font-semibold tracking-tighter">
          Gestion de la BDD
        </p>
        <BddManagerSection />
      </div>
    </div>
  );
};

export default ParamsPage;
